# translate the sequences into windows

In [1]:
import pandas as pd
import numpy as np
from scripts import AA_window as aaw
import random

## imports

In [2]:
expert_df = pd.read_excel("expert curated/expert_sub_nonsub_120424.xlsx").set_index("entry")
expert_df.head(5)

,name,gene_name,organism,dataset,len_sequence,start,stop,sequence
entry,,,,,,,,
P16234,PGFRA_HUMAN,PDGFRA,HUMAN,NONSUB,1089,525,549,MGTSHPAFLVLGCLLTGLSLILCQLSLPSILPNENEKVVQLNSSFS...
P50895,BCAM_HUMAN,BCAM,HUMAN,NONSUB,628,547,571,MEPPDAPAQARGAPRLLLLAVLLAAHPDAQAEVRLSVPPLVEVMRG...
P16066,ANPRA_HUMAN,NPR1,HUMAN,NONSUB,1061,474,494,MPGPRRPAGSRLRLLLLLLLPPLLLLLRGSHAGNLTVAVVLPLANT...
Q8IUW5,RELL1_HUMAN,RELL1,HUMAN,NONSUB,271,58,81,MAPRALPGSAVLAAAVFVGGAVSSPLVAPDNGSSRTLHSRTETTPS...
P05556,ITB1_HUMAN,ITGB1,HUMAN,NONSUB,798,729,751,MNLQPIFWIGLISSVCCVFAQTDENRCLKANAKSCGECIQAGPNCG...

In [3]:
uniprot_df = pd.read_excel("UniProt_SS_N_out.xlsx").set_index("entry")[["len_sequence", "sequence"]]
mem_df = pd.read_excel("all_Annots_N_out.xlsx", "Preds").set_index("entry")
mem_df = mem_df[(mem_df["annotation_software"]=="Membranome")&(mem_df["subcellular_location"]=="Plasma memb.")].dropna(subset="tmd")
mem_ind = mem_df.index.tolist()
mem_df = pd.concat([mem_df, uniprot_df.loc[mem_ind]], axis=1)
mem_df.to_excel("pm_membranome_validated.xlsx")
mem_df

,annotation_software,name,gene_name,organism,dataset,len_sequence,protein_domains,protein_category,len_signal,len_ecto,...,len_endo,start_pos_TMD,stop_pos_TMD,jmd_n,tmd,jmd_c,top_prediction (Annot. AI / DB),subcellular_location,len_sequence,sequence
entry,,,,,,,,,,,,,,,,,,,,,
P48551,Membranome,INAR2_HUMAN,IFNAR2,HUMAN,SUBEXPERT,515.0,"['S', 'o', 'M', 'i']",ssTMD N-out (signal peptide),NaN,NaN,...,NaN,243.0,267.0,GQESESAESA,KIGGIITVFLIALVLTSTIVTLKWI,GYICLRNSLP,NaN,Plasma memb.,515,MLLSQNAFIFRSLNLVLMVYISLVFGISYDSPDYTDESCTFKISLR...
Q86YL7,Membranome,PDPN_HUMAN,PDPN,HUMAN,SUBEXPERT,162.0,"['S', 'o', 'M', 'i']",ssTMD N-out (signal peptide),NaN,NaN,...,NaN,126.0,155.0,DTQTTVEKDG,LSTVTLVGIIVGVLLAIGFIGAIIVVVMRK,MSGRYSP,NaN,Plasma memb.,162,MWKVSALLFVLGSASLWVLAEGASTGQPEDDTETTGLEGGVAMPGA...
P35590,Membranome,TIE1_HUMAN,TIE1,HUMAN,SUBEXPERT,1138.0,"['S', 'o', 'M', 'i']",ssTMD N-out (signal peptide),NaN,NaN,...,NaN,758.0,784.0,QESRAAEEGL,DQQLILAVVGSVSATCLTILAALLTLV,CIRRSCLHRR,NaN,Plasma memb.,1138,MVWRVPPFLLPILFLASHVGAAVDLTLLANLRLTDPQRFFLTCVSG...
P19022,Membranome,CADH2_HUMAN,CDH2,HUMAN,SUBEXPERT,906.0,"['S', 'o', 'M', 'i']",ssTMD N-out (signal peptide),NaN,NaN,...,NaN,725.0,746.0,IVGAGLGTGA,IIAILLCIIILLILVLMFVVWM,KRRDKERQAK,NaN,Plasma memb.,906,MCRIAGALRTLLPLLAALLQASVEASGEIALCKTGFPEDVYSAVLS...
Q13308,Membranome,PTK7_HUMAN,PTK7,HUMAN,SUBEXPERT,1070.0,"['S', 'o', 'M', 'i']",ssTMD N-out (signal peptide),NaN,NaN,...,NaN,704.0,725.0,GSPPPYKMIQ,TIGLSVGAAVAYIIAVLGLMFY,CKKRCKAKRL,NaN,Plasma memb.,1070,MGAARGSPARPRRLPLLSVLLLPLLGGTQTAIVFIKQPSSQDALQG...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
P54762,Membranome,EPHB1_HUMAN,EPHB1,HUMAN,NaN,984.0,"['S', 'o', 'M', 'i']",ssTMD N-out (signal peptide),NaN,NaN,...,NaN,541.0,562.0,YKSELREQLP,LIAGSAAAGVVFVVSLVAISIV,CSRKRAYSKE,NaN,Plasma memb.,984,MALDYLLLLLLASAVAAMEETLMDTRTATAELGWTANPASGWEEVS...
Q92823,Membranome,NRCAM_HUMAN,NRCAM,HUMAN,NaN,1304.0,"['S', 'o', 'M', 'i']",ssTMD N-out (signal peptide),NaN,NaN,...,NaN,1169.0,1190.0,SRQVDIATQG,WFIGLMCAVALLILILLIVCFI,RRNKGGKYPV,NaN,Plasma memb.,1304,MQLKIMPKKKRLSAGRVPLILFLCQMISALEVPLDPKLLEDLVQPP...
P05538,Membranome,DQB2_HUMAN,HLA-DQB2,HUMAN,NaN,268.0,"['S', 'o', 'M', 'i']",ssTMD N-out (signal peptide),NaN,NaN,...,NaN,231.0,251.0,AQSESAQSKM,LSGIGGFVLGLIFLGLGLIIR,HRGQKGPRGP,NaN,Plasma memb.,268,MSWKMALQIPGGFWAAAVTVMLVMLSTPVAEARDFPKDFLVQFKGM...
Q15262,Membranome,PTPRK_HUMAN,PTPRK,HUMAN,NaN,1439.0,"['S', 'o', 'M', 'i']",ssTMD N-out (signal peptide),NaN,NaN,...,NaN,754.0,775.0,AKQTDRVVKI,AGISAGILVFILLLLVVILIVK,KSKLAKKRKD,NaN,Plasma memb.,1439,MDTTAAAALPAFVALLLLSPWPLLGSAQGQFSAGGCTFDDGPGACD...
Q86Z14,Membranome,KLOTB_HUMAN,KLB,HUMAN,NaN,1044.0,"['o', 'M', 'i']",ssTMD N-out,NaN,NaN,...,NaN,997.0,1017.0,VCLFLVQKKP,LIFLGCCFFSTLVLLLSIAIF,QRQKRRKFWK,NaN,Plasma memb.,1044,MKPGCAAGSPGNEWIFFSTDEITTRYRNTMSNGGLQRSVILSALIL...

In [4]:
mean_df = pd.read_excel("mean_weight/arithmetic_mean_all_annots_for_refining.xlsx").set_index("entry")
mean_df.head(5)

,start_pos_TMD,stop_pos_TMD,sequence
entry,,,
P48551,244,266,MLLSQNAFIFRSLNLVLMVYISLVFGISYDSPDYTDESCTFKISLR...
Q86YL7,129,152,MWKVSALLFVLGSASLWVLAEGASTGQPEDDTETTGLEGGVAMPGA...
P35590,762,785,MVWRVPPFLLPILFLASHVGAAVDLTLLANLRLTDPQRFFLTCVSG...
P09803,711,733,MGARCRSFSALLLLLQVSSWLCQELEPESCSPGFSSEVYTFPVPER...
P19022,724,745,MCRIAGALRTLLPLLAALLQASVEASGEIALCKTGFPEDVYSAVLS...

## expert_df

In [5]:
use_expert = expert_df.reset_index()
window_expert_N = aaw.AAwindowrizer.get_aa_window_df(df=use_expert, column_id="entry", column_seq="sequence", window_size=4,
                                                   column_aa_position="start", start_pos=True, start_set_positive=True).show_df()
window_expert_N

           window_left window_right  label  start  norm_intersect_pos
ID
P16234__0         LRSE         LTVA      1    525            0.482094
P16234__-1        TLRS         ELTV      0    524            0.481175
P16234__1         RSEL         TVAA      0    526            0.483012
P16234__-2        PTLR         SELT      0    523            0.480257
P16234__2         SELT         VAAA      0    527            0.483930
...                ...          ...    ...    ...                 ...
P48551__1         SAKI         GGII      0    245            0.475728
P48551__-2        SAES         AKIG      0    242            0.469903
P48551__2         AKIG         GIIT      0    246            0.477670
P48551__-3        ESAE         SAKI      0    241            0.467961
P48551__3         KIGG         IITV      0    247            0.479612

[1120 rows x 5 columns]

In [6]:
# we set the final validation set to 200

In [7]:
index_expert = window_expert_N.index.tolist()

In [8]:
expert_val = random.sample(index_expert, 200)

In [9]:
expert_val_df_N = window_expert_N.loc[expert_val]
#expert_val_df_N.to_excel("expert_val_df_N.xlsx")

In [10]:
expert_test_df_N = window_expert_N.drop(expert_val)
#expert_test_df_N.to_excel("expert_test_df_N.xlsx")

In [11]:
window_expert_C = aaw.AAwindowrizer.get_aa_window_df(df=use_expert, column_id="entry", column_seq="sequence", window_size=4,
                                                     column_aa_position="stop", start_pos=False, start_set_positive=True).show_df()
index_expert = window_expert_C.index.tolist()
expert_val = random.sample(index_expert, 200)

expert_val_df_C = window_expert_C.loc[expert_val]
#expert_val_df_C.to_excel("expert_val_df_C.xlsx")
expert_test_df_C = window_expert_C.drop(expert_val)
#expert_test_df_C.to_excel("expert_test_df_C.xlsx")

## mem_df

In [14]:
use_mem = mem_df.reset_index()
window_mem_N = aaw.AAwindowrizer.get_aa_window_df(df=use_mem, column_id="entry", column_seq="sequence", window_size=4,
                                                     column_aa_position="start_pos_TMD", start_pos=True, start_set_positive=True).show_df().drop_duplicates(subset=["window_right", "window_left"]).dropna(how="any")
print(window_mem_N)
window_mem_N = window_mem_N.drop(window_mem_N[window_mem_N["window_right"]==""].index)
index_mem = window_mem_N.index.tolist()
mem_val = random.sample(index_mem, 200)

mem_val_df_N = window_mem_N.loc[mem_val]
mem_val_df_N.to_excel("mem_val_df_N.xlsx")
mem_test_df_N = window_mem_N.drop(mem_val)
mem_test_df_N.to_excel("mem_test_df_N.xlsx")

           window_left window_right  label  start_pos_TMD  norm_intersect_pos
ID
P48551__0         AESA         KIGG      1            243            0.471845
P48551__-1        SAES         AKIG      0            242            0.469903
P48551__1         ESAK         IGGI      0            244            0.473786
P48551__-2        ESAE         SAKI      0            241            0.467961
P48551__2         SAKI         GGII      0            245            0.475728
...                ...          ...    ...            ...                 ...
Q86Z14__1         KKPL         IFLG      0            998            0.955939
Q86Z14__-2        LVQK         KPLI      0            995            0.953065
Q86Z14__2         KPLI         FLGC      0            999            0.956897
Q86Z14__-3        FLVQ         KKPL      0            994            0.952107
Q86Z14__3         PLIF         LGCC      0           1000            0.957854

[7026 rows x 5 columns]

In [15]:
use_mem = mem_df.reset_index()
window_mem_C = aaw.AAwindowrizer.get_aa_window_df(df=use_mem, column_id="entry", column_seq="sequence", window_size=4,
                                                     column_aa_position="stop_pos_TMD", start_pos=False, start_set_positive=True).show_df().drop_duplicates(subset=["window_right", "window_left"]).dropna(how="any")
window_mem_C = window_mem_C.drop(window_mem_C[window_mem_C["window_right"]==""].index)
index_mem = window_mem_C.index.tolist()
mem_val = random.sample(index_mem, 200)

mem_val_df_C = window_mem_C.loc[mem_val]
mem_val_df_C.to_excel("mem_val_df_C.xlsx")
mem_test_df_C = window_mem_C.drop(mem_val)
mem_test_df_C.to_excel("mem_test_df_C.xlsx")

In [ ]:
stop

## mean_df

In [ ]:
all_annot = pd.read_excel("all_Annots_N_out.xlsx", "Preds")
all_annot

In [ ]:
all_annot.columns

In [ ]:
all_annot_drop = all_annot.dropna(subset="name")

In [ ]:
all_annot_drop

In [ ]:
use_mean = mean_df.reset_index()
window_mean_N = aaw.AAwindowrizer.get_aa_window_df(df=use_mean, column_id="entry", column_seq="sequence", window_size=4,
                                                     column_aa_position="start_pos_TMD", start_pos=True, start_set_positive=False).show_df()
window_mean_N_plus = aaw.AAwindowrizer.modify_label_by_ident_column(window_mean_N, all_annot_drop, "entry")
window_mean_N_plus

In [ ]:
window_mean_N_plus_new = window_mean_N_plus.show_df().dropna(how="any")
window_mean_N_plus_new_new = window_mean_N_plus_new.drop(window_mean_N_plus_new[window_mean_N_plus_new["window_right"]==""].index)
window_mean_N_plus_new_new

In [ ]:
# drop duplicates the smart way
pos_N = window_mean_N_plus_new_new[window_mean_N_plus_new_new["label"]==1][["window_right", "window_left"]]
neg_N = window_mean_N_plus_new_new[window_mean_N_plus_new_new["label"]==0][["window_right", "window_left"]]
neg_N

In [ ]:
for index_1, rows_1 in pos_N.iterrows():
    if rows_1.to_list() in neg_N.to_numpy().tolist():
        ind_N = neg_N.to_numpy().tolist().index(rows_1.to_list())
        neg_N = neg_N.drop(neg_N.index.tolist()[ind_N])
neg_N_new_index = neg_N.index.tolist()

In [ ]:
window_mean_N_plus_final = pd.concat([neg_N, pos_N]).drop_duplicates()
window_mean_N_plus_new_new_new = window_mean_N_plus_new_new.loc[window_mean_N_plus_final.index.tolist()].sample(frac=1)
"""window_mean_N_plus_new_new_new["weights"] = window_mean_N_plus_new_new_new["weights"].replace(0, np.nan)
window_mean_N_plus_new_new_new = window_mean_N_plus_new_new_new.dropna(how="any")"""
window_mean_N_plus_new_new_new

In [ ]:
index_mean = window_mean_N_plus_new_new_new[window_mean_N_plus_new_new_new["label"]==1].sort_values("weights", ascending=False).index.tolist()[:100]
index_mean2 = window_mean_N_plus_new_new_new[window_mean_N_plus_new_new_new["label"]==0].sort_values("weights", ascending=False).index.tolist()[:600]
index_full = index_mean.extend(index_mean2)
mean_val = random.sample(index_mean, 200)

mean_val_df_N = window_mean_N_plus_new_new_new.loc[mean_val]
mean_val_df_N.to_excel("mean_val_df_N_balance2.xlsx")
mean_test_df_N = window_mean_N_plus_new_new_new.drop(mean_val)
mean_test_df_N.to_excel("mean_test_df_N_balance2.xlsx")

In [ ]:
# c term n mean

In [ ]:
use_mean = mean_df.reset_index()
window_mean_C = aaw.AAwindowrizer.get_aa_window_df(df=use_mean, column_id="entry", column_seq="sequence", window_size=4,
                                                     column_aa_position="stop_pos_TMD", start_pos=False, start_set_positive=False).show_df()
window_mean_C_plus = aaw.AAwindowrizer.modify_label_by_ident_column(window_mean_C, all_annot_drop, "entry").show_df()
window_mean_C_plus

In [ ]:
window_mean_C_plus_new = window_mean_C_plus.dropna(how="any")
window_mean_C_plus_new_new = window_mean_C_plus_new.drop(window_mean_C_plus_new[window_mean_C_plus_new["window_right"]==""].index)
window_mean_C_plus_new_new

In [ ]:
pos_C = window_mean_C_plus_new_new[window_mean_C_plus_new_new["label"]==1][["window_right", "window_left"]]
neg_C = window_mean_C_plus_new_new[window_mean_C_plus_new_new["label"]==0][["window_right", "window_left"]]
pos_C

In [ ]:
for index_1, rows_1 in pos_C.iterrows():
    if rows_1.to_list() in neg_C.to_numpy().tolist():
        ind_C = neg_C.to_numpy().tolist().index(rows_1.to_list())
        neg_C = neg_C.drop(neg_C.index.tolist()[ind_C])
neg_C_new_index = neg_C.index.tolist()

In [ ]:
window_mean_C_plus_final = pd.concat([neg_C, pos_C]).drop_duplicates()
window_mean_C_plus_new_new_new = window_mean_C_plus_new_new.loc[window_mean_C_plus_final.index.tolist()].sample(frac=1)
"""window_mean_C_plus_new_new_new["weights"] = window_mean_C_plus_new_new_new["weights"].replace(0, np.nan)
window_mean_C_plus_new_new_new = window_mean_C_plus_new_new_new.dropna(how="any")"""
window_mean_C_plus_new_new_new

In [ ]:
index_mean = window_mean_C_plus_new_new_new[window_mean_C_plus_new_new_new["label"]==1].sort_values("weights", ascending=False).index.tolist()[:100]
index_mean2 = window_mean_C_plus_new_new_new[window_mean_C_plus_new_new_new["label"]==0].sort_values("weights", ascending=False).index.tolist()[:600]
index_full = index_mean.extend(index_mean2)
mean_val = random.sample(index_mean, 200)

mean_val_df_C = window_mean_C_plus_new_new_new.loc[mean_val]
mean_val_df_C.to_excel("mean_val_df_C_balance2.xlsx")
mean_test_df_C = window_mean_C_plus_new_new_new.drop(mean_val)
mean_test_df_C.to_excel("mean_test_df_C_balance2.xlsx")