# translate the sequences into windows

In [18]:
import pandas as pd
import numpy as np
from scripts import AA_window as aaw
import random

## imports

In [7]:
expert_df = pd.read_excel("expert curated/expert_sub_nonsub_120424.xlsx").set_index("entry")
expert_df.head(5)

,name,gene_name,organism,dataset,len_sequence,start,stop,sequence
entry,,,,,,,,
P16234,PGFRA_HUMAN,PDGFRA,HUMAN,NONSUB,1089,525,549,MGTSHPAFLVLGCLLTGLSLILCQLSLPSILPNENEKVVQLNSSFS...
P50895,BCAM_HUMAN,BCAM,HUMAN,NONSUB,628,547,571,MEPPDAPAQARGAPRLLLLAVLLAAHPDAQAEVRLSVPPLVEVMRG...
P16066,ANPRA_HUMAN,NPR1,HUMAN,NONSUB,1061,474,494,MPGPRRPAGSRLRLLLLLLLPPLLLLLRGSHAGNLTVAVVLPLANT...
Q8IUW5,RELL1_HUMAN,RELL1,HUMAN,NONSUB,271,58,81,MAPRALPGSAVLAAAVFVGGAVSSPLVAPDNGSSRTLHSRTETTPS...
P05556,ITB1_HUMAN,ITGB1,HUMAN,NONSUB,798,729,751,MNLQPIFWIGLISSVCCVFAQTDENRCLKANAKSCGECIQAGPNCG...

In [9]:
mem_df = pd.read_excel("PM_Membranom/pm_membranome_N_out.xlsx").set_index("entry")
mem_df.head(5)

,annotation_software,name,gene_name,organism,dataset,len_sequence,protein_domains,protein_category,len_TMD,start_pos_TMD,stop_pos_TMD,jmd_n,tmd,jmd_c,subcellular_location,sequence
entry,,,,,,,,,,,,,,,,
P48551,Membranome,INAR2_HUMAN,IFNAR2,HUMAN,SUBEXPERT,515,"['S', 'o', 'M', 'i']",ssTMD N-out (signal peptide),25,243,267,GQESESAESA,KIGGIITVFLIALVLTSTIVTLKWI,GYICLRNSLP,Plasma memb.,MLLSQNAFIFRSLNLVLMVYISLVFGISYDSPDYTDESCTFKISLR...
Q86YL7,Membranome,PDPN_HUMAN,PDPN,HUMAN,SUBEXPERT,162,"['S', 'o', 'M', 'i']",ssTMD N-out (signal peptide),30,126,155,DTQTTVEKDG,LSTVTLVGIIVGVLLAIGFIGAIIVVVMRK,MSGRYSP,Plasma memb.,MWKVSALLFVLGSASLWVLAEGASTGQPEDDTETTGLEGGVAMPGA...
P35590,Membranome,TIE1_HUMAN,TIE1,HUMAN,SUBEXPERT,1138,"['S', 'o', 'M', 'i']",ssTMD N-out (signal peptide),27,758,784,QESRAAEEGL,DQQLILAVVGSVSATCLTILAALLTLV,CIRRSCLHRR,Plasma memb.,MVWRVPPFLLPILFLASHVGAAVDLTLLANLRLTDPQRFFLTCVSG...
P19022,Membranome,CADH2_HUMAN,CDH2,HUMAN,SUBEXPERT,906,"['S', 'o', 'M', 'i']",ssTMD N-out (signal peptide),22,725,746,IVGAGLGTGA,IIAILLCIIILLILVLMFVVWM,KRRDKERQAK,Plasma memb.,MCRIAGALRTLLPLLAALLQASVEASGEIALCKTGFPEDVYSAVLS...
Q13308,Membranome,PTK7_HUMAN,PTK7,HUMAN,SUBEXPERT,1070,"['S', 'o', 'M', 'i']",ssTMD N-out (signal peptide),22,704,725,GSPPPYKMIQ,TIGLSVGAAVAYIIAVLGLMFY,CKKRCKAKRL,Plasma memb.,MGAARGSPARPRRLPLLSVLLLPLLGGTQTAIVFIKQPSSQDALQG...

In [8]:
mean_df = pd.read_excel("mean_weight/arithmetic_mean_all_annots_for_refining.xlsx").set_index("entry")
mean_df.head(5)

,start_pos_TMD,stop_pos_TMD,sequence
entry,,,
P48551,244,266,MLLSQNAFIFRSLNLVLMVYISLVFGISYDSPDYTDESCTFKISLR...
Q86YL7,129,152,MWKVSALLFVLGSASLWVLAEGASTGQPEDDTETTGLEGGVAMPGA...
P35590,762,785,MVWRVPPFLLPILFLASHVGAAVDLTLLANLRLTDPQRFFLTCVSG...
P09803,711,733,MGARCRSFSALLLLLQVSSWLCQELEPESCSPGFSSEVYTFPVPER...
P19022,724,745,MCRIAGALRTLLPLLAALLQASVEASGEIALCKTGFPEDVYSAVLS...

## expert_df

In [17]:
use_expert = expert_df.reset_index()
window_expert_N = aaw.AAwindowrizer.get_aa_window_df(df=use_expert, column_id="entry", column_seq="sequence", window_size=4,
                                                   column_aa_position="start", start_pos=True, start_set_positive=True).show_df()
window_expert_N

           window_left window_right  label  start  norm_intersect_pos
ID
P16234__0         LRSE         LTVA      1    525            0.482094
P16234__-1        TLRS         ELTV      0    524            0.481175
P16234__1         RSEL         TVAA      0    526            0.483012
P16234__-2        PTLR         SELT      0    523            0.480257
P16234__2         SELT         VAAA      0    527            0.483930
...                ...          ...    ...    ...                 ...
P48551__1         SAKI         GGII      0    245            0.475728
P48551__-2        SAES         AKIG      0    242            0.469903
P48551__2         AKIG         GIIT      0    246            0.477670
P48551__-3        ESAE         SAKI      0    241            0.467961
P48551__3         KIGG         IITV      0    247            0.479612

[1120 rows x 5 columns]

In [19]:
# we set the final validation set to 200

In [20]:
index_expert = window_expert_N.index.tolist()

In [21]:
expert_val = random.sample(index_expert, 200)

In [25]:
expert_val_df_N = window_expert_N.loc[expert_val]
#expert_val_df_N.to_excel("expert_val_df_N.xlsx")

In [26]:
expert_test_df_N = window_expert_N.drop(expert_val)
#expert_test_df_N.to_excel("expert_test_df_N.xlsx")

In [30]:
window_expert_C = aaw.AAwindowrizer.get_aa_window_df(df=use_expert, column_id="entry", column_seq="sequence", window_size=4,
                                                     column_aa_position="stop", start_pos=False, start_set_positive=True).show_df()
index_expert = window_expert_C.index.tolist()
expert_val = random.sample(index_expert, 200)

expert_val_df_C = window_expert_C.loc[expert_val]
#expert_val_df_C.to_excel("expert_val_df_C.xlsx")
expert_test_df_C = window_expert_C.drop(expert_val)
#expert_test_df_C.to_excel("expert_test_df_C.xlsx")

## mem_df

In [41]:
use_mem = mem_df.reset_index()
window_mem_N = aaw.AAwindowrizer.get_aa_window_df(df=use_mem, column_id="entry", column_seq="sequence", window_size=4,
                                                     column_aa_position="start_pos_TMD", start_pos=True, start_set_positive=True).show_df().drop_duplicates(subset=["window_right", "window_left"]).dropna(how="any")
window_mem_N = window_mem_N.drop(window_mem_N[window_mem_N["window_right"]==""].index)
index_mem = window_mem_N.index.tolist()
mem_val = random.sample(index_mem, 200)

mem_val_df_N = window_mem_N.loc[mem_val]
#mem_val_df_N.to_excel("mem_val_df_N.xlsx")
mem_test_df_N = window_mem_N.drop(mem_val)
#mem_test_df_N.to_excel("mem_test_df_N.xlsx")

In [40]:
use_mem = mem_df.reset_index()
window_mem_C = aaw.AAwindowrizer.get_aa_window_df(df=use_mem, column_id="entry", column_seq="sequence", window_size=4,
                                                     column_aa_position="stop_pos_TMD", start_pos=False, start_set_positive=True).show_df().drop_duplicates(subset=["window_right", "window_left"]).dropna(how="any")
window_mem_C = window_mem_C.drop(window_mem_C[window_mem_C["window_right"]==""].index)
index_mem = window_mem_C.index.tolist()
mem_val = random.sample(index_mem, 200)

mem_val_df_C = window_mem_C.loc[mem_val]
#mem_val_df_C.to_excel("mem_val_df_C.xlsx")
mem_test_df_C = window_mem_C.drop(mem_val)
#mem_test_df_C.to_excel("mem_test_df_C.xlsx")

## mean_df

In [50]:
all_annot = pd.read_excel("all_Annots_N_out.xlsx", "Preds")
all_annot

,entry,annotation_software,name,gene_name,organism,dataset,len_sequence,protein_domains,protein_category,len_signal,len_ecto,len_TMD,len_endo,start_pos_TMD,stop_pos_TMD,jmd_n,tmd,jmd_c,top_prediction (Annot. AI / DB),subcellular_location
0,P48551,UniProt,INAR2_HUMAN,IFNAR2,HUMAN,SUBEXPERT,515.0,"['S', 'o', 'M', 'i']",ssTMD N-out (signal peptide),26.0,217.0,21.0,251.0,244.0,264.0,QESESAESAK,IGGIITVFLIALVLTSTIVTL,KWIGYICLR,2/8,Membrane;PM;Secreted
1,P48551,Phobius,INAR2_HUMAN,IFNAR2,HUMAN,SUBEXPERT,515.0,"['S', 'o', 'M', 'i']",ssTMD N-out (signal peptide),NaN,NaN,25.0,NaN,244.0,268.0,QESESAESAK,IGGIITVFLIALVLTSTIVTLKWIG,YICLRNSLP,NaN,NaN
2,P48551,TMHMM,INAR2_HUMAN,IFNAR2,HUMAN,SUBEXPERT,515.0,"['S', 'o', 'M', 'i']",ssTMD N-out (signal peptide),NaN,NaN,23.0,NaN,7.0,29.0,MLLSQN,AFIFRSLNLVLMVYISLVFGISY,DSPDYTDES,NaN,NaN
3,P48551,PolyPhobius,INAR2_HUMAN,IFNAR2,HUMAN,SUBEXPERT,515.0,"['S', 'o', 'M', 'i']",ssTMD N-out (signal peptide),26.0,216.0,22.0,251.0,243.0,265.0,GQESESAESA,KIGGIITVFLIALVLTSTIVTLK,WIGYICLRNS,NaN,NaN
4,P48551,SPOCTOPUS,INAR2_HUMAN,IFNAR2,HUMAN,SUBEXPERT,515.0,"['S', 'o', 'M', 'i']",ssTMD N-out (signal peptide),30.0,214.0,21.0,250.0,245.0,266.0,ESESAESAKI,GGIITVFLIALVLTSTIVTLKW,IGYICLRNSL,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32092,Q86Z14,TOPCONS,KLOTB_HUMAN,KLB,HUMAN,NaN,1044.0,"['i', 'M', 'o', 'M', 'i']","dsTMD, signal peptide possibly not-predicted",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32093,Q86Z14,DeepTMHMM,KLOTB_HUMAN,KLB,HUMAN,NaN,1044.0,"['o', 'M', 'i']",ssTMD N-out,0.0,996.0,21.0,27.0,997.0,1017.0,VCLFLVQKKP,LIFLGCCFFSTLVLLLSIAIF,QRQKRRKFW,NaN,NaN
32094,Q86Z14,Membranome,KLOTB_HUMAN,KLB,HUMAN,NaN,1044.0,"['o', 'M', 'i']",ssTMD N-out,NaN,NaN,21.0,NaN,997.0,1017.0,VCLFLVQKKP,LIFLGCCFFSTLVLLLSIAIF,QRQKRRKFWK,NaN,Plasma memb.
32095,Q86Z14,arithmetic mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.0,NaN,997.0,1017.0,VCLFLVQKKP,LIFLGCCFFSTLVLLLSIAIF,QRQKRRKFWK,NaN,NaN
32096,Q86Z14,Expert curated,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [51]:
all_annot.columns

Index(['entry', 'annotation_software', 'name', 'gene_name', 'organism',
       'dataset', 'len_sequence', 'protein_domains', 'protein_category',
       'len_signal', 'len_ecto', 'len_TMD', 'len_endo', 'start_pos_TMD',
       'stop_pos_TMD', 'jmd_n', 'tmd', 'jmd_c',
       'top_prediction (Annot. AI / DB)', 'subcellular_location'],
      dtype='object')

In [52]:
all_annot_drop = all_annot.dropna(subset="name")

In [53]:
all_annot_drop

,entry,annotation_software,name,gene_name,organism,dataset,len_sequence,protein_domains,protein_category,len_signal,len_ecto,len_TMD,len_endo,start_pos_TMD,stop_pos_TMD,jmd_n,tmd,jmd_c,top_prediction (Annot. AI / DB),subcellular_location
0,P48551,UniProt,INAR2_HUMAN,IFNAR2,HUMAN,SUBEXPERT,515.0,"['S', 'o', 'M', 'i']",ssTMD N-out (signal peptide),26.0,217.0,21.0,251.0,244.0,264.0,QESESAESAK,IGGIITVFLIALVLTSTIVTL,KWIGYICLR,2/8,Membrane;PM;Secreted
1,P48551,Phobius,INAR2_HUMAN,IFNAR2,HUMAN,SUBEXPERT,515.0,"['S', 'o', 'M', 'i']",ssTMD N-out (signal peptide),NaN,NaN,25.0,NaN,244.0,268.0,QESESAESAK,IGGIITVFLIALVLTSTIVTLKWIG,YICLRNSLP,NaN,NaN
2,P48551,TMHMM,INAR2_HUMAN,IFNAR2,HUMAN,SUBEXPERT,515.0,"['S', 'o', 'M', 'i']",ssTMD N-out (signal peptide),NaN,NaN,23.0,NaN,7.0,29.0,MLLSQN,AFIFRSLNLVLMVYISLVFGISY,DSPDYTDES,NaN,NaN
3,P48551,PolyPhobius,INAR2_HUMAN,IFNAR2,HUMAN,SUBEXPERT,515.0,"['S', 'o', 'M', 'i']",ssTMD N-out (signal peptide),26.0,216.0,22.0,251.0,243.0,265.0,GQESESAESA,KIGGIITVFLIALVLTSTIVTLK,WIGYICLRNS,NaN,NaN
4,P48551,SPOCTOPUS,INAR2_HUMAN,IFNAR2,HUMAN,SUBEXPERT,515.0,"['S', 'o', 'M', 'i']",ssTMD N-out (signal peptide),30.0,214.0,21.0,250.0,245.0,266.0,ESESAESAKI,GGIITVFLIALVLTSTIVTLKW,IGYICLRNSL,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32090,Q86Z14,PolyPhobius,KLOTB_HUMAN,KLB,HUMAN,NaN,1044.0,"['o', 'M', 'i']",ssTMD N-out,NaN,996.0,21.0,27.0,997.0,1018.0,VCLFLVQKKP,LIFLGCCFFSTLVLLLSIAIFQ,RQKRRKFWKA,NaN,NaN
32091,Q86Z14,SPOCTOPUS,KLOTB_HUMAN,KLB,HUMAN,NaN,1044.0,"['i', 'M', 'o', 'M', 'i']","dsTMD, signal peptide possibly not-predicted",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32092,Q86Z14,TOPCONS,KLOTB_HUMAN,KLB,HUMAN,NaN,1044.0,"['i', 'M', 'o', 'M', 'i']","dsTMD, signal peptide possibly not-predicted",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32093,Q86Z14,DeepTMHMM,KLOTB_HUMAN,KLB,HUMAN,NaN,1044.0,"['o', 'M', 'i']",ssTMD N-out,0.0,996.0,21.0,27.0,997.0,1017.0,VCLFLVQKKP,LIFLGCCFFSTLVLLLSIAIF,QRQKRRKFW,NaN,NaN
32094,Q86Z14,Membranome,KLOTB_HUMAN,KLB,HUMAN,NaN,1044.0,"['o', 'M', 'i']",ssTMD N-out,NaN,NaN,21.0,NaN,997.0,1017.0,VCLFLVQKKP,LIFLGCCFFSTLVLLLSIAIF,QRQKRRKFWK,NaN,Plasma memb.

In [55]:
use_mean = mean_df.reset_index()
window_mean_N = aaw.AAwindowrizer.get_aa_window_df(df=use_mean, column_id="entry", column_seq="sequence", window_size=4,
                                                     column_aa_position="start_pos_TMD", start_pos=True, start_set_positive=False).show_df()
window_mean_N_plus = aaw.AAwindowrizer.modify_label_by_ident_column(window_mean_N, all_annot_drop, "entry")
window_mean_N_plus

In [59]:
window_mean_N_plus_new = window_mean_N_plus.show_df().dropna(how="any")
window_mean_N_plus_new_new = window_mean_N_plus_new.drop(window_mean_N_plus_new[window_mean_N_plus_new["window_right"]==""].index)
window_mean_N_plus_new_new

,window_left,window_right,label,start_pos_TMD,norm_intersect_pos,weights
ID,,,,,,
P48551__0,ESAK,IGGI,1,244,0.473786,4
P48551__-1,AESA,KIGG,1,243,0.471845,2
P48551__1,SAKI,GGII,0,245,0.475728,1
P48551__-2,SAES,AKIG,0,242,0.469903,1
P48551__2,AKIG,GIIT,0,246,0.477670,1
...,...,...,...,...,...,...
Q86Z14__1,KKPL,IFLG,0,998,0.955939,1
Q86Z14__-2,LVQK,KPLI,0,995,0.953065,1
Q86Z14__2,KPLI,FLGC,0,999,0.956897,1
Q86Z14__-3,FLVQ,KKPL,0,994,0.952107,1
Q86Z14__3,PLIF,LGCC,0,1000,0.957854,1

In [74]:
# drop duplicates the smart way
pos_N = window_mean_N_plus_new_new[window_mean_N_plus_new_new["label"]==1][["window_right", "window_left"]]
neg_N = window_mean_N_plus_new_new[window_mean_N_plus_new_new["label"]==0][["window_right", "window_left"]]
neg_N

           window_right window_left
ID
P48551__1          GGII        SAKI
P48551__-2         AKIG        SAES
P48551__2          GIIT        AKIG
P48551__-3         SAKI        ESAE
P48551__3          IITV        KIGG
...                 ...         ...
Q86Z14__1          IFLG        KKPL
Q86Z14__-2         KPLI        LVQK
Q86Z14__2          FLGC        KPLI
Q86Z14__-3         KKPL        FLVQ
Q86Z14__3          LGCC        PLIF

[14870 rows x 2 columns]

In [76]:
for index_1, rows_1 in pos_N.iterrows():
    if rows_1.to_list() in neg_N.to_numpy().tolist():
        ind_N = neg_N.to_numpy().tolist().index(rows_1.to_list())
        neg_N = neg_N.drop(neg_N.index.tolist()[ind_N])
neg_N_new_index = neg_N.index.tolist()

In [83]:
window_mean_N_plus_final = pd.concat([neg_N, pos_N]).drop_duplicates()
window_mean_N_plus_new_new_new = window_mean_N_plus_new_new.loc[window_mean_N_plus_final.index.tolist()].sample(frac=1)
window_mean_N_plus_new_new_new

,window_left,window_right,label,start_pos_TMD,norm_intersect_pos,weights
ID,,,,,,
Q96KC8__1,SNAE,LALL,1,154,0.277978,2
Q6ZMC9__-2,HGAS,GAST,0,260,0.792683,1
Q96MS0__3,PAFL,AGSG,0,895,0.645743,1
Q92673__-2,AARS,TDVA,0,2134,0.963866,1
P28067__-1,DLLE,NVLC,0,230,0.881226,1
...,...,...,...,...,...,...
Q04900__-2,RKST,FDAA,0,161,0.817259,1
P13224__3,GALA,AQLA,0,153,0.742718,1
Q0V8T7__-1,VPSD,LAVI,1,1236,0.947126,2
P28068__0,QTLK,VSVS,1,219,0.832700,5
Q3U4N7__1,SVLP,LAVL,0,167,0.484058,1

In [101]:
index_mean = window_mean_N_plus_new_new_new.sort_values("weights", ascending=False).index.tolist()[:100]
index_mean2 = window_mean_N_plus_new_new_new.sort_values("weights", ascending=True).index.tolist()[:600]
index_full = index_mean.extend(index_mean2)
mean_val = random.sample(index_mean, 200)

mean_val_df_N = window_mean_N_plus_new_new_new.loc[mean_val]
mean_val_df_N.to_excel("mean_val_df_N_balance.xlsx")
mean_test_df_N = window_mean_N_plus_new_new_new.drop(mean_val)
mean_test_df_N.to_excel("mean_test_df_N_balance.xlsx")

In [86]:
# c term n mean

In [88]:
use_mean = mean_df.reset_index()
window_mean_C = aaw.AAwindowrizer.get_aa_window_df(df=use_mean, column_id="entry", column_seq="sequence", window_size=4,
                                                     column_aa_position="stop_pos_TMD", start_pos=False, start_set_positive=False).show_df()
window_mean_C_plus = aaw.AAwindowrizer.modify_label_by_ident_column(window_mean_C, all_annot_drop, "entry").show_df()
window_mean_C_plus

,window_left,window_right,label,stop_pos_TMD,norm_intersect_pos,weights
ID,,,,,,
P48551__0,TLKW,IGYI,0,266,0.516505,1
P48551__-1,VTLK,WIGY,1,265,0.514563,2
P48551__1,LKWI,GYIC,0,267,0.518447,1
P48551__-2,IVTL,KWIG,1,264,0.512621,2
P48551__2,KWIG,YICL,0,268,0.520388,1
...,...,...,...,...,...,...
Q86Z14__1,AIFQ,RQKR,0,1018,0.975096,1
Q86Z14__-2,LSIA,IFQR,0,1015,0.972222,1
Q86Z14__2,IFQR,QKRR,0,1019,0.976054,1
Q86Z14__-3,LLSI,AIFQ,0,1014,0.971264,1
Q86Z14__3,FQRQ,KRRK,0,1020,0.977011,1

In [89]:
window_mean_C_plus_new = window_mean_C_plus.dropna(how="any")
window_mean_C_plus_new_new = window_mean_C_plus_new.drop(window_mean_C_plus_new[window_mean_C_plus_new["window_right"]==""].index)
window_mean_C_plus_new_new

,window_left,window_right,label,stop_pos_TMD,norm_intersect_pos,weights
ID,,,,,,
P48551__0,TLKW,IGYI,0,266,0.516505,1
P48551__-1,VTLK,WIGY,1,265,0.514563,2
P48551__1,LKWI,GYIC,0,267,0.518447,1
P48551__-2,IVTL,KWIG,1,264,0.512621,2
P48551__2,KWIG,YICL,0,268,0.520388,1
...,...,...,...,...,...,...
Q86Z14__1,AIFQ,RQKR,0,1018,0.975096,1
Q86Z14__-2,LSIA,IFQR,0,1015,0.972222,1
Q86Z14__2,IFQR,QKRR,0,1019,0.976054,1
Q86Z14__-3,LLSI,AIFQ,0,1014,0.971264,1
Q86Z14__3,FQRQ,KRRK,0,1020,0.977011,1

In [93]:
pos_C = window_mean_C_plus_new_new[window_mean_C_plus_new_new["label"]==1][["window_right", "window_left"]]
neg_C = window_mean_C_plus_new_new[window_mean_C_plus_new_new["label"]==0][["window_right", "window_left"]]
pos_C

           window_right window_left
ID
P48551__-1         WIGY        VTLK
P48551__-2         KWIG        IVTL
Q86YL7__0          MRKM        IVVV
Q86YL7__-2         VVMR        AIIV
P35590__-1         CIRR        LTLV
...                 ...         ...
Q9R1C6__1          RSRR        CSLQ
P56378__0          RAAD        VYKI
Q9NNZ3__0          RKVK        YIAF
P23299__0          RSKK        LSYI
Q86Z14__0          QRQK        IAIF

[5219 rows x 2 columns]

In [94]:
for index_1, rows_1 in pos_C.iterrows():
    if rows_1.to_list() in neg_C.to_numpy().tolist():
        ind_C = neg_C.to_numpy().tolist().index(rows_1.to_list())
        neg_C = neg_C.drop(neg_C.index.tolist()[ind_C])
neg_C_new_index = neg_C.index.tolist()

In [97]:
window_mean_C_plus_final = pd.concat([neg_C, pos_C]).drop_duplicates()
window_mean_C_plus_new_new_new = window_mean_C_plus_new_new.loc[window_mean_C_plus_final.index.tolist()].sample(frac=1)
window_mean_C_plus_new_new_new.head(20)

,window_left,window_right,label,stop_pos_TMD,norm_intersect_pos,weights
ID,,,,,,
O15270__-2,LFGY,LRDF,0,86,0.153025,1
Q96KJ4__-1,HWGT,CILV,0,662,0.943020,1
Q8NC54__-3,AVVY,ITYH,0,214,0.807547,1
Q9BYE9__-3,MTMA,FVCV,0,1173,0.895420,1
Q8K348__1,WACQ,DRQC,0,137,0.277890,1
P26150__3,YRYI,PPFN,0,312,0.836461,1
Q3U0X8__-3,LLFG,LGVR,0,554,0.920266,1
Q9NRR2__-3,VSCV,LLAK,0,301,0.937695,1
Q9EQS9__2,GLRR,SSHR,0,979,0.781949,1
Q99LE3__2,LLYY,EILA,0,239,0.783607,1
Q80X80__-3,TVLG,WMLQ,0,28,0.039660,1
Q7Z5N4__1,ALVL,HGQN,1,2031,0.917759,2
Q99NH8__1,WAVA,RGRQ,0,194,0.854626,1
Q6DFX2__-2,ALMW,WFWP,0,338,0.694045,1
O60896__0,LVVW,RSKR,1,139,0.939189,4
P36898__3,RYKR,QEAR,0,152,0.302789,1
Q9BCZ4__0,YIVI,QRLS,1,48,0.252632,3
P15421__-2,ILIS,YCIR,0,74,0.948718,1
P55808__3,FKLN,NRRN,0,166,0.922222,1
Q5T7P8__-3,VFLF,LFWK,0,78,0.152941,1

In [102]:
index_mean = window_mean_C_plus_new_new_new.sort_values("weights", ascending=False).index.tolist()[:100]
index_mean2 = window_mean_C_plus_new_new_new.sort_values("weights", ascending=True).index.tolist()[:600]
index_full = index_mean.extend(index_mean2)
mean_val = random.sample(index_mean, 200)

mean_val_df_C = window_mean_C_plus_new_new_new.loc[mean_val]
mean_val_df_C.to_excel("mean_val_df_C_balance.xlsx")
mean_test_df_C = window_mean_C_plus_new_new_new.drop(mean_val)
mean_test_df_C.to_excel("mean_test_df_C_balance.xlsx")