# TMDrefined Preds for arithmetic mean with threshold = 2

In [1]:
#imports
import numpy as np
import pandas as pd
import os
import glob
import scripts.ML_TMDrefined as ml_ref
import scripts.Translate_TMDrefined as t_ref
import scripts.StandardConfig as stdc

In [2]:
# get all the files
path, sep = stdc.find_folderpath()
path_labels = f"{path}{sep}label_am2_data{sep}"
list_df_analysis_tags = glob.glob(f"{path_labels}*.xlsx")
list_df_analysis_tags

['/home/wernerfeiler/PycharmProjects/TMDrefined/label_am2_data/am2_test_C.xlsx',
 '/home/wernerfeiler/PycharmProjects/TMDrefined/label_am2_data/am2_test_N.xlsx',
 '/home/wernerfeiler/PycharmProjects/TMDrefined/label_am2_data/am2_train_C.xlsx',
 '/home/wernerfeiler/PycharmProjects/TMDrefined/label_am2_data/am2_train_N.xlsx',
 '/home/wernerfeiler/PycharmProjects/TMDrefined/label_am2_data/am_label_single_start_pos_TMD_thresh=2_CPP_top.xlsx',
 '/home/wernerfeiler/PycharmProjects/TMDrefined/label_am2_data/am_label_single_stop_pos_TMD_thresh=2_CPP_top.xlsx',
 '/home/wernerfeiler/PycharmProjects/TMDrefined/label_am2_data/first_of_top60_scales_cat.xlsx']

## N-term Pred with threshold 2 for arithmetic mean

In [3]:
test_am_N2 = pd.read_excel('/home/wernerfeiler/PycharmProjects/TMDrefined/label_am2_data/am2_test_N.xlsx').set_index("ID")
train_am_N2 = pd.read_excel('/home/wernerfeiler/PycharmProjects/TMDrefined/label_am2_data/am2_train_N.xlsx',).set_index("ID")
am_N2_top_CPP = pd.read_excel('/home/wernerfeiler/PycharmProjects/TMDrefined/label_am2_data/first_of_top60_scales_cat.xlsx')

In [4]:
am_N2_top_CPP.head(15)

,Unnamed: 0,scale_id,category,subcategory,scale_name,scale_description
0,0,LINS030109,ASA/Volume,Accessible surface area (ASA),Hydrophilic ASA (folded proteins),% Hydrophilic accessible surfaces vs win3 of w...
1,1,ARGP820103,ASA/Volume,Buried,Buried,Membrane-buried preference parameters (Argos e...
2,2,LINS030105,ASA/Volume,Hydrophobic ASA,Hydrophobic ASA (folded proteins),Hydrophobic median accessible surfaces of whol...
3,3,BASU050101,ASA/Volume,Partial specific volume,Interactivity,Interactivity scale obtained from the contact ...
4,4,FAUJ880103,ASA/Volume,Volume,Volume,Normalized van der Waals volume (Fauchere et a...
5,5,JOND920101,Composition,AA composition,AA composition,Relative frequency of occurrence (Jones et al....
6,6,NAKH920101,Composition,AA composition,"Membrane proteins (single-spanning, INT)",AA composition of CYT of single-spanning prote...
7,7,KUMS000103,Composition,AA composition,Proteins of thermophiles,Distribution of amino acid residues in the alp...
8,8,DIGM050101,Composition,AA composition (surface),Hydrostatic pressure,"Hydrostatic Pressure asymmetry index, PAI (Di ..."
9,9,FUKS010102,Composition,AA composition (surface),Proteins of mesophiles (INT),Surface composition of amino acids in intracel...
10,10,FUKS010101,Composition,AA composition (surface),Proteins of thermophiles (INT),Surface composition of amino acids in intracel...
11,11,CEDJ970103,Composition,Membrane proteins (MPs),Membrane proteins,Composition of amino acids in membrane protein...
12,12,FUKS010108,Composition,Membrane proteins (MPs),Nuclear proteins (interior),Interior composition of amino acids in nuclear...
13,13,NAKH900113,Composition,Unclassified (Composition),Average Composition,Ratio of average and computed composition (Nak...
14,14,GRAR740101,Composition,Unclassified (Composition),Substitution Frequency,"Composition (Grantham, 1974)"

In [5]:
train_am_N2.head(5)

,window_left,window_right,label,start_pos_TMD,norm_intersect_pos
ID,,,,,
INAR2_HUMAN__0,ESAK,IGGI,1,244,0.473786
INAR2_HUMAN__-1,AESA,KIGG,1,243,0.471845
INAR2_HUMAN__1,SAKI,GGII,0,245,0.475728
INAR2_HUMAN__-2,SAES,AKIG,0,242,0.469903
INAR2_HUMAN__2,AKIG,GIIT,0,246,0.477670

In [6]:
am_N2_top_CPP["category"].unique()

array(['ASA/Volume', 'Composition', 'Conformation', 'Energy', 'Others',
       'Polarity', 'Shape', 'Structure-Activity'], dtype=object)

In [7]:
train_am_N2.columns

Index(['window_left', 'window_right', 'label', 'start_pos_TMD',
       'norm_intersect_pos'],
      dtype='object')

In [8]:
train_N_drop = train_am_N2.drop_duplicates(subset=['window_left', 'window_right']).dropna()
train_N_drop

,window_left,window_right,label,start_pos_TMD,norm_intersect_pos
ID,,,,,
INAR2_HUMAN__0,ESAK,IGGI,1,244,0.473786
INAR2_HUMAN__-1,AESA,KIGG,1,243,0.471845
INAR2_HUMAN__1,SAKI,GGII,0,245,0.475728
INAR2_HUMAN__-2,SAES,AKIG,0,242,0.469903
INAR2_HUMAN__2,AKIG,GIIT,0,246,0.477670
...,...,...,...,...,...
KLOTB_HUMAN__-1,VQKK,PLIF,0,996,0.954023
KLOTB_HUMAN__1,KKPL,IFLG,0,998,0.955939
KLOTB_HUMAN__-2,LVQK,KPLI,0,995,0.953065
KLOTB_HUMAN__2,KPLI,FLGC,0,999,0.956897
KLOTB_HUMAN__3,PLIF,LGCC,0,1000,0.957854

In [9]:
train_N_drop.describe()

              label  start_pos_TMD  norm_intersect_pos
count  15252.000000   15252.000000        15252.000000
mean       0.275243     477.720955            0.668755
std        0.446651     650.193938            0.264797
min        0.000000       2.000000            0.003968
25%        0.000000     153.000000            0.518519
50%        0.000000     312.000000            0.756443
75%        1.000000     629.000000            0.877551
max        1.000000   14455.000000            0.996416

In [10]:
test_am_N2.describe()

            label  start_pos_TMD  norm_intersect_pos
count  300.000000     300.000000          300.000000
mean     0.176667     568.936667            0.700387
std      0.382024     639.323738            0.223580
min      0.000000      14.000000            0.037234
25%      0.000000     227.000000            0.640430
50%      0.000000     398.000000            0.770362
75%      0.000000     696.250000            0.851124
max      1.000000    4157.000000            0.971344

In [11]:
test_N_drop = test_am_N2.drop_duplicates(subset=['window_left', 'window_right'])

In [12]:
test_N_drop.describe()

            label  start_pos_TMD  norm_intersect_pos
count  282.000000     282.000000          282.000000
mean     0.184397     563.468085            0.695994
std      0.388497     653.891108            0.229450
min      0.000000      14.000000            0.037234
25%      0.000000     215.500000            0.627007
50%      0.000000     349.000000            0.770362
75%      0.000000     683.500000            0.853899
max      1.000000    4157.000000            0.971344

In [13]:
aaontology_colors = {'ASA/Volume': [54,128,180], 
                     'Polarity': [253,220,34], 
                     'Structure-Activity': [140,94,86], 
                     'Composition': [255,146,50],
                     'Others': [127,127,127], 
                     'Shape': [55,192,206], 
                     'Conformation': [61,159,71],
                     'Energy': [213,65,65]
                    }

In [14]:
aaontology_colors_hex = {'ASA/Volume': "#3680b4", 
                         'Polarity': "#fddc22", 
                         'Structure-Activity': "#8c5e56", 
                         'Composition': "#ff9232",
                         'Others': "#7f7f7f", 
                         'Shape': "#37c0ce", 
                         'Conformation': "#3d9f47",
                         'Energy': "#d54141"
                        }

In [15]:
am_N2_CPP_list = am_N2_top_CPP["scale_id"].to_numpy().tolist()
am_N2_CPP_list = [feature.split("-")[2] for feature in am_N2_top_CPP["feature"].to_numpy().tolist()]
am_N2_CPP_list = ['LINS030107', 'NISK800101', 'MIYS990105', 'BLAS910101', 'GRAR740102', 'MEIH800101', 'VINM940101']

KeyError: 'feature'

In [ ]:
trainN2_scale_df, train_N2_label_df = t_ref.aa_numeric_by_scale(feature_df=train_N_drop[["window_left", "window_right"]], label_df=train_N_drop["label"], scale_df_filter=am_N2_CPP_list, mode="weighted")
trainN2_scale_df

In [ ]:
train_N2_label_df

In [ ]:
testN2_scale_df, test_N2_label_df = t_ref.aa_numeric_by_scale(feature_df=test_N_drop[["window_left", "window_right"]], label_df=test_N_drop["label"], scale_df_filter=am_N2_CPP_list, mode="weighted")
testN2_scale_df

In [ ]:
test_N2_label_df

In [ ]:
# now the BIG algorithm, get all the treeeeeez

In [ ]:
#best_params= {'bootstrap': [True], 'class_weight': ['balanced'], 'criterion': ['gini'], 'max_depth': [15], 'max_leaf_nodes': [20], 'n_estimators': [340], 'n_jobs': [6]}
#param_grid = {'bootstrap': [True], 'ccp_alpha': [0], 'class_weight': ['balanced_subsample'], 'criterion': ['gini'], 'max_depth': [10], 'max_leaf_nodes': [80], 'max_samples': [0.6], 'n_estimators': [300], 'n_jobs': [-1], 'verbose': [0]}
AM_N2_forest = ml_ref.ForestTMDrefind.make_forest(trainN2_scale_df, train_N2_label_df, job_name="am_N2_drop(3)", n_jobs=-1)
AM_N2_forest.fetch_a_tree()
AM_N2_forest.hyperparameter_summary(save_table=True)
AM_N2_forest.feature_importance()

In [ ]:
test_labels_pred = AM_N2_forest.predict_labels(testN2_scale_df) 
test_labels_pred

In [ ]:
AM_N2_forest.test_predict_quality(label_test=test_N2_label_df, label_pred=test_labels_pred, cm_save=True)

In [ ]:
# P05067, APP, 701
seq = "MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVREVCSEQAETGPCRAMISRWYFDVTEGKCAPFFYGGCGGNRNNFDTEEYCMAVCGSAMSQSLLKTTQEPLARDPVKLPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEVEPVDARPAADRGLTTRPGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN"

In [ ]:
AM_N2_forest.pred_from_seq("APP", seq, 701)

In [ ]:
seq = "MEPPDAPAQARGAPRLLLLAVLLAAHPDAQAEVRLSVPPLVEVMRGKSVILDCTPTGTHDHYMLEWFLTDRSGARPRLASAEMQGSELQVTMHDTRGRSPPYQLDSQGRLVLAEAQVGDERDYVCVVRAGAAGTAEATARLNVFAKPEATEVSPNKGTLSVMEDSAQEIATCNSRNGNPAPKITWYRNGQRLEVPVEMNPEGYMTSRTVREASGLLSLTSTLYLRLRKDDRDASFHCAAHYSLPEGRHGRLDSPTFHLTLHYPTEHVQFWVGSPSTPAGWVREGDTVQLLCRGDGSPSPEYTLFRLQDEQEEVLNVNLEGNLTLEGVTRGQSGTYGCRVEDYDAADDVQLSKTLELRVAYLDPLELSEGKVLSLPLNSSAVVNCSVHGLPTPALRWTKDSTPLGDGPMLSLSSITFDSNGTYVCEASLPTVPVLSRTQNFTLLVQGSPELKTAEIEPKADGSWREGDEVTLICSARGHPDPKLSWSQLGGSPAEPIPGRQGWVSSSLTLKVTSALSRDGISCEASNPHGNKRHVFHFGTVSPQTSQAGVAVMAVAVSVGLLLLVVAVFYCVRRKGGPCCRQRREKGAPPPGEPGLSHSGSEQPEQTGLLMGGASGGARGGSGGFGDEC"
AM_N2_forest.pred_from_seq("BCAM", seq, 548)